// User
export const REQUEST_USER = 'REQUEST_USER';
export const RECEIVE_USER = 'RECEIVE_USER';
export const ERROR_RECEIVE_USER = 'ERROR_RECEIVE_USER';

export const REQUEST_SIGN_IN = 'REQUEST_SIGN_IN';
export const SUCCESS_SIGN_IN = 'SUCCESS_SIGN_IN';
export const ERROR_SIGN_IN = 'ERROR_SIGN_IN';

export const REQUEST_SIGN_UP = 'REQUEST_SIGN_UP';
export const SUCCESS_SIGN_UP = 'SUCCESS_SIGN_UP';
export const ERROR_SIGN_UP = 'ERROR_SIGN_UP';

export const REQUEST_SIGN_OUT = 'REQUEST_SIGN_OUT';
export const SUCCESS_SIGN_OUT = 'SUCCESS_SIGN_OUT';
export const ERROR_SIGN_OUT = 'ERROR_SIGN_OUT';

// List
export const REQUEST_LIST = 'REQUEST_LIST';
export const RECEIVE_LIST = 'RECEIVE_LIST';
export const ERROR_RECEIVE_LIST = 'ERROR_RECEIVE_LIST';
export const RECEIVE_LIST_BY_ID = 'RECEIVE_LIST_BY_ID';
export const CREATE_ITEM = 'CREATE_ITEM';